-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE alert (
                       id bigint PRIMARY KEY,
                       tmp_user_id bigint,
                       topic character varying(255)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX alert_pkey ON alert(id int8_ops);


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE notice (
                        id bigint PRIMARY KEY,
                        contents character varying(255),
                        creator character varying(255),
                        images text[],
                        part character varying(255),
                        title character varying(255)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX notice_pkey ON notice(id int8_ops);


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE tmp_user (
                          id bigint PRIMARY KEY,
                          auth integer,
                          client_token character varying(255)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX tmp_user_pkey ON tmp_user(id int8_ops);

