-- DDL generated by Postico 2.0 RC 6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

set search_path to app_dev;

CREATE TABLE app_dev.app_users (
                                   user_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                   username character varying(30) NOT NULL,
                                   nickname character varying(255) UNIQUE NOT NULL,
                                   points bigint DEFAULT 0,
                                   is_opt_in boolean DEFAULT false,
                                   playground_id bigint UNIQUE ,
                                   playground_token character varying(500),
--                                    os_type character varying(20),
--                                    password character varying(600) NOT NULL,
                                   created_at timestamp without time zone,
                                   updated_at timestamp without time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "USER_pkey" ON app_dev.app_users(user_id int8_ops);


-- DDL generated by Postico 2.0 RC 6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE app_dev.mission (
                                 mission_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                 title character varying(300) NOT NULL,
                                 level integer NOT NULL,
                                 display boolean,
                                 profile_image text[]
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "STAMP_pkey" ON app_dev.mission(mission_id int8_ops);

-- DDL generated by Postico 2.0 RC 6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE app_dev.stamp (
                               id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                               contents character varying(500) NOT NULL,
                               images text[],
                               created_at timestamp without time zone,
                               updated_at timestamp without time zone,
                               user_id bigint REFERENCES app_dev.app_users(user_id) ON DELETE CASCADE,
                               mission_id bigint
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "MISSION_pkey" ON app_dev.stamp(id int8_ops);

-- Table Definition ----------------------------------------------

CREATE TABLE app_dev.push_token
(
    playground_id bigint REFERENCES app_dev.app_users(playground_id),
    token         text[],
    created_at    timestamp without time zone,
    updated_at    timestamp without time zone,
    PRIMARY KEY (playground_id, token)
);

alter table app_dev.push_token
    owner to makers;

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "PUSH_TOKEN_pkey" ON app_dev.app_users(playground_id int8_ops);

-- Table Definition ----------------------------------------------

CREATE TABLE app_dev.notification_option
(
    opt_id bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES app_dev.app_users(user_id) UNIQUE ,
    all_opt_in boolean DEFAULT false,
    part_opt_in boolean DEFAULT false,
    news_opt_in boolean DEFAULT false
);

alter table app_dev.notification_option
    owner to makers;

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "PUSH_OPTION_pkey" ON app_dev.app_users(user_id int8_ops);
