### 푸시 수신 여부 조회
GET {{server}}/api/v2/user/opt-in
Authorization: {{accessToken}}


### 푸시 수신 상세 동의 조회
GET {{server}}/api/v2/user/opt-in/detail
Authorization: {{accessToken}}

### 푸시 수신 여부 변경
PATCH {{server}}/api/v2/user/opt-in
Content-Type: application/json
Authorization: {{accessToken}}

< ./data/patch-optin.json


### 푸시 수신 상세 동의 변경
PATCH {{server}}/api/v2/user/opt-in/detail
Content-Type: application/json
Authorization: {{accessToken}}

< ./data/patch-optin-detail.json


