AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Sopt makers App Backend DEV - Spring Boot JAR on AWS Lambda with SnapStart

Globals:
  Function:
    Timeout: 300                  # 최대 실행 시간 (초)
    MemorySize: 3072              # 메모리 (MB) - 프로젝트 크기에 따라 조정
    Runtime: java21               # Java 버전

Parameters:
  S3Bucket:
    Type: String
    Default: ""
    Description: S3 bucket containing the Lambda JAR
  S3Key:
    Type: String
    Default: ""
    Description: S3 key (path) to the Lambda JAR file
  Profile:
    Type: String
    Default: "lambda-dev"
    Description: Spring profile to use
#  RedisHost:
#    Type: String
#    Description: Redis Host URL
#  RedisPort:
#    Type: String
#    Description: Redis Port
#  RedisPassword:
#    Type: String
#    Description: Redis Password


Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-api"
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
      Handler: org.sopt.app.LambdaHandler
      SnapStart:
        ApplyOn: PublishedVersions        # SnapStart 활성화
      AutoPublishAlias: live
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref Profile
          #          REDIS_HOST: !Ref RedisHost
          #          REDIS_PORT: !Ref RedisPort
          #          REDIS_PASSWORD: !Ref RedisPassword
          TZ: Asia/Seoul
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
      Events:
        ApiProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      EndpointConfiguration: REGIONAL    # 👈 [추가] 이 한 줄이 핵심입니다!
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
        AllowCredentials: "'false'"

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "[https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev](https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev)"