name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write  # [중요] PR에 리뷰어를 추가할 수 있는 권한 부여

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: jher235, kyoooooong